# Generated by Django 4.2.6 on 2023-11-23 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_candidate', models.BooleanField(default=False)),
                ('is_employer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuestoDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.CharField(max_length=128)),
                ('rut_empresa', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=128)),
                ('direccion', models.CharField(max_length=128)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('myapp.baseuser',),
        ),
        migrations.CreateModel(
            name='CandidatoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_1', models.CharField(blank=True, choices=[('Base de datos (SQL)', 'Base de datos (SQL)'), ('Programacion (Python)', 'Programacion (Python)'), ('Programacion (Java)', 'Programacion (Java)'), ('Programacion Front End', 'Programacion Front End'), ('Programacion Back End', 'Programacion Back End'), ('Tecnologias Cloud', 'Tecnologias Cloud')], max_length=100, null=True)),
                ('competencia_2', models.CharField(blank=True, choices=[('Base de datos (SQL)', 'Base de datos (SQL)'), ('Programacion (Python)', 'Programacion (Python)'), ('Programacion (Java)', 'Programacion (Java)'), ('Programacion Front End', 'Programacion Front End'), ('Programacion Back End', 'Programacion Back End'), ('Tecnologias Cloud', 'Tecnologias Cloud')], max_length=100, null=True)),
                ('competencia_3', models.CharField(blank=True, choices=[('Base de datos (SQL)', 'Base de datos (SQL)'), ('Programacion (Python)', 'Programacion (Python)'), ('Programacion (Java)', 'Programacion (Java)'), ('Programacion Front End', 'Programacion Front End'), ('Programacion Back End', 'Programacion Back End'), ('Tecnologias Cloud', 'Tecnologias Cloud')], max_length=100, null=True)),
                ('competencia_4', models.CharField(blank=True, choices=[('Base de datos (SQL)', 'Base de datos (SQL)'), ('Programacion (Python)', 'Programacion (Python)'), ('Programacion (Java)', 'Programacion (Java)'), ('Programacion Front End', 'Programacion Front End'), ('Programacion Back End', 'Programacion Back End'), ('Tecnologias Cloud', 'Tecnologias Cloud')], max_length=100, null=True)),
                ('competencia_5', models.CharField(blank=True, choices=[('Base de datos (SQL)', 'Base de datos (SQL)'), ('Programacion (Python)', 'Programacion (Python)'), ('Programacion (Java)', 'Programacion (Java)'), ('Programacion Front End', 'Programacion Front End'), ('Programacion Back End', 'Programacion Back End'), ('Tecnologias Cloud', 'Tecnologias Cloud')], max_length=100, null=True)),
                ('competencia_6', models.CharField(blank=True, choices=[('Base de datos (SQL)', 'Base de datos (SQL)'), ('Programacion (Python)', 'Programacion (Python)'), ('Programacion (Java)', 'Programacion (Java)'), ('Programacion Front End', 'Programacion Front End'), ('Programacion Back End', 'Programacion Back End'), ('Tecnologias Cloud', 'Tecnologias Cloud')], max_length=100, null=True)),
                ('comentarios_extra', models.TextField(blank=True, null=True)),
                ('archivo1', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('archivo2', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('archivo3', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('puesto_de_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.puestodetrabajo')),
            ],
            options={
                'abstract': False,
            },
            bases=('myapp.baseuser',),
        ),
    ]
