# Generated by Django 4.2.6 on 2023-11-29 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_candidatoperfil_puesto_de_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidato')),
                ('puesto_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.puestodetrabajo')),
            ],
        ),
    ]
