# Generated by Django 4.2.6 on 2023-11-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatoperfil',
            name='puesto_de_trabajo',
        ),
    ]
