# Generated by Django 4.2.6 on 2023-11-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_candidatoperfil_puesto_de_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='puesto_de_trabajo',
        ),
    ]
