# Generated by Django 4.2.6 on 2023-11-29 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_candidato_puesto_de_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='puesto_de_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.puestodetrabajo'),
        ),
    ]
