# Generated by Django 4.2.6 on 2023-12-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_candidatoperfil_puesto_de_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='confirm_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='new_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
