# Generated by Django 4.2.6 on 2023-12-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_baseuser_confirm_password_baseuser_new_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='new_password',
        ),
    ]
