# Generated by Django 4.2.6 on 2023-12-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_baseuser_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatoperfil',
            name='mostrar_actualmente1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidatoperfil',
            name='mostrar_actualmente2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidatoperfil',
            name='mostrar_actualmente3',
            field=models.BooleanField(default=True),
        ),
    ]
