# Generated by Django 4.2.6 on 2023-12-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_candidatoperfil_mostrar_actualmente1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatoperfil',
            name='mostrar_actualmente1',
        ),
        migrations.RemoveField(
            model_name='candidatoperfil',
            name='mostrar_actualmente2',
        ),
        migrations.RemoveField(
            model_name='candidatoperfil',
            name='mostrar_actualmente3',
        ),
    ]
