# Generated by Django 4.2.6 on 2023-12-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_candidatoperfil_mostrar_actualmente1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('candidato', 'Candidato'), ('empleador', 'Empleador')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
