# Generated by Django 4.2.6 on 2023-12-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_baseuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='user_type',
        ),
    ]
